from colorama import Fore, Back, Style

def printBanner():
    print(Style.BRIGHT+"                                " + Back.LIGHTGREEN_EX + Fore.BLACK + "  WELCOME TO \"SUITCASE ADVENTURE\"!  \033[0m                  "+Back.BLUE + Fore.BLACK +"                                                  ")
    print(Style.RESET_ALL+"       "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+"[[__]]"+Style.RESET_ALL+"              " + Back.LIGHTYELLOW_EX + Fore.BLACK + "  Your suitcase is lost in a major airport.  " + Back.RESET + Fore.RESET + "              "+Back.BLUE + Fore.BLACK +"           "+Back.WHITE+"/ |"+Back.BLUE+"                      "+Back.LIGHTWHITE_EX+"( `   )"+ Back.BLUE+"")
    print(Style.RESET_ALL+"   "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+";-----------.|"+Style.RESET_ALL+"        " + Back.RED + Fore.BLACK + "  Your mission: find it with the least flights.  " + Back.RESET + Fore.RESET + "            "+Back.BLUE + Fore.BLACK +"          "+Back.WHITE+"|  |"+Back.BLUE+"                    "+Back.LIGHTWHITE_EX+"(    )    `)"+ Back.BLUE+"                  "+Back.LIGHTWHITE_EX+"(  )"+ Back.BLUE+"")
    print(Style.RESET_ALL+"   "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+"|           ||"+Style.RESET_ALL+"      " + Back.LIGHTBLUE_EX + Fore.BLACK + "  Explore the world and make eco-conscious choices!  " + Back.RESET + Fore.RESET + "          "+Back.BLUE + Fore.BLACK +"      "+Back.WHITE+"|"+Back.BLUE+"   "+Back.WHITE+"|  |"+Back.BLUE+"    "+Back.WHITE+"/-|"+Back.BLUE+"          "+Back.LIGHTWHITE_EX+"(_   (_ .  _) _)"+ Back.BLUE+"              "+Back.LIGHTWHITE_EX+"( `  ) . )"+ Back.BLUE+"")
    print(Style.RESET_ALL+"   "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+"|           ||"+Style.RESET_ALL+"                                                                     "+Back.BLUE + Fore.BLACK +"      *"+Back.WHITE+"|__|  |____----"+Back.BLUE+"                                     "+Back.LIGHTWHITE_EX+"(_, _(  ,_)_)"+ Back.BLUE+"")
    print(Style.RESET_ALL+"   "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+"|           ||"+Style.RESET_ALL+"         " + Back.MAGENTA + Fore.BLACK + "  Let's leave a positive impact on the planet!  " + Back.RESET + Fore.RESET + "            "+Back.BLUE + Fore.BLACK +"      "+Back.WHITE+"|"+Back.BLUE+"   "+Back.WHITE+"|  |"+Back.BLUE+"    "+Back.WHITE+"\-|"+Back.BLUE+"")
    print(Style.RESET_ALL+"   "+Back.YELLOW+Fore.BLACK+Style.BRIGHT+"|___________|/"+Style.RESET_ALL+"                                                                     "+Back.BLUE + Fore.BLACK +"          "+Back.WHITE+"|  |"+Back.BLUE+"                             "+Back.LIGHTWHITE_EX+"(  _ )"+ Back.BLUE+"")
    print(Style.RESET_ALL+"                               " + Back.WHITE + Fore.LIGHTWHITE_EX + "  Made in Metropolia, Finland, 2024  " + Back.RESET + Fore.RESET + "                  "+Back.BLUE + Fore.BLACK +"           "+Back.WHITE+"\_|"+Back.BLUE+"                           "+Back.LIGHTWHITE_EX+"(_  _(_ ,)"+ Back.BLUE+"")
    print(Style.RESET_ALL+"                                                                                      " + Back.BLUE +"")
    print(Style.RESET_ALL+"")